---
- name: install libselinux-python
  yum: name=libselinux-python state=present

- name: set selinux to permissive
  selinux: policy=targeted state=permissive

- name: disable iptables
  service: name=iptables state=stopped enabled=no

- name: bootstrap epel-release install
  copy: src=../files/ansible-bootstrap-epel.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name: epel-release install
  yum: name=epel-release
       enablerepo=ansible-bootstrap-epel
       state=present

- name: epel repository enable
  ini_file: dest=/etc/yum.repos.d/epel.repo
            section=epel
            option=enabled
            value=1
