---
- name: mha1
  ip: 192.168.50.51
  role: 
    - node
- name: mha2
  ip: 192.168.50.52
  role: 
    - node
- name: mha3
  ip: 192.168.50.53
  role: 
    - node
- name: mha4
  ip: 192.168.50.54
  role: 
    - manager
    - monitor
