---
- name: mysql01
  ip: 192.168.50.61
  box: chef/ubuntu-13.10
  box_check_update: no
  provider: virtualbox
  provider_config:
    --memory: 384
    --cpuexecutioncap: 50
  role: 
    - db_master
    - manager
    - monitor
