---
- name: create mysql folders
  file: path={{ item }} owner=mysql group=mysql mode=0755 state=directory
  with_items:
      - "{{ mysql_data_dir }}"
      - "{{ mysql_run_dir }}"
      - "{{ mysql_binlog_dir }}"
      - "{{ mysql_log_dir }}"
      - "{{ mysql_tmp_dir }}"

- name: install mysql system tables
  command: mysql_install_db --user=mysql --datadir="{{ mysql_data_dir }}" creates="{{ mysql_data_dir }}/mysql"

- name: copy my.cnf
  template: src="{{ ansible_os_family }}-my.cnf.j2" dest="{{ my_cnf_dir }}/my.cnf" owner=mysql group=mysql mode=0644
  notify: restart mysql

- name: check if the innodb log files are open
  command: lsof {{ item }}
  ignore_errors: yes
  changed_when: false
  register: iblogfile_open
  with_items:
    - "{{ mysql_data_dir }}/ib_logfile0"
    - "{{ mysql_data_dir }}/ib_logfile1"

- name: check the size of the innodb log files
  stat: path={{ item.item }} get_md5=no
  ignore_errors: yes
  register: iblogfile_stat
  with_items: iblogfile_open.results
  when: item.rc != 0

- name: remove innodb log files if incorrect size
  file: path={{ item.item.item }}  state=absent
  with_items: iblogfile_stat.results
  when: item.stat.size is defined and item.stat.size != "{{ mysql_innodb_logfile_size_mb }} * (1024 * 1024)"

- name: start mysql
  service: name=mysql state=started enabled=yes
