---
- name: ensure perl mysql dbd is installed
  yum: name=perl-DBD-MySQL state=present

- name: check if mha node package is installed
  command: rpm -q "{{ mha_node_file }}"
  register: mha_node_package
  ignore_errors: yes
  when: mha_install == 'node'

- name: install mha node package
  command: rpm -ivh "{{ mha_download_location }}{{ mha_node_file }}.rpm" 
  when: mha_install == 'node' and mha_node_package.rc == 1

- name: install mha manager prequisites on red hat family hosts
  yum: name={{ item }} state=present
  with_items: mha_pkgs
  when: mha_install == 'manager'

- name: check if mha manager package is installed
  command: rpm -q "{{ mha_manager_file }}"
  register: mha_manager_package
  ignore_errors: yes
  when: mha_install == 'manager'

- name: install mha manager package
  command: rpm -ivh "{{ mha_download_location }}{{ mha_manager_file }}.rpm"
  when: mha_install == 'manager' and mha_manager_package.rc == 1
